INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (1,'54512 Declaration Trail','Alexi Totaro hospital',150);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (2,'1092 Spaight Terrace','Demetri Doige hospital',56);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (3,'32 Mcbride Pass','Lacee Silversmid hospital',131);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (4,'845 Dahle Trail','Kelley Veart hospital',96);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (5,'636 Kropf Trail','Ronnica Kidds hospital',130);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (6,'7 Pond Crossing','Ellary Padberry hospital',139);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (7,'2 Fairfield Place','Town Tolchar hospital',122);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (8,'44 Sullivan Place','Cathryn Marlor hospital',84);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (9,'814 Brickson Park Avenue','Riccardo Esplin hospital',102);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (10,'7115 Loeprich Point','Carlene Sawdy hospital',101);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (11,'24 Dayton Trail','Davey Guesford hospital',73);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (12,'15 Del Sol Plaza','Jessie Rawling hospital',68);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (13,'07 Mallory Center','Farleigh Rofe hospital',69);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (14,'202 Prairie Rose Junction','Tandie De Paoli hospital',76);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (15,'02236 Valley Edge Trail','Nerte Cheverell hospital',113);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (16,'6407 Lien Lane','Tessa Duchart hospital',92);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (17,'2403 Ridgeview Hill','Candace Mackleden hospital',56);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (18,'43235 Vermont Way','Evangeline Skewis hospital',75);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (19,'72 Moulton Drive','Silvio O''Carney hospital',148);
INSERT INTO zdravstveni_dom(id,naslov,ime,kapaciteta) VALUES (20,'058 Park Meadow Street','Tamqrah Durbridge hospital',145);
